---
title: "News"
---

# EHDEN HMB v0.1.5

* Correct bug in analysis settings
* Update package website

# EHDEN HMB v0.1.4

* Fix bug in baseline characteristics (typo in analysis settings)
* Corrections to the study website


# EHDEN HMB v0.1.3

* Update cohort definitions
    - add baseline procedures
    - add baseline drugs
* Include procedure prevalence at baseline [-365,0]

# EHDEN HMB v0.1.2

* Update cohort definitions
    - rerun drug exposure with Capr
    - rerun procedures with Capr
    - add time restraints to nsaids
    - add hmb cohort without hysterectomy censor
* Add secondary treatment sequence including procedures 

# EHDEN HMB v0.1.1

* Add study website
* Update cohort definitions for denominator
* Addition of executeStudy.R file to automate execution
* add age strata [under 30, 30-45, 45-55]


# EHDEN HMB v0.1.0

* First release of study code for EHDEN HMB
    * Add Incidence Analysis
    * Add Baseline Characteristics 
    * Add Treatment Patterns
    * Add Procedure Analysis

# EHDEN HMB v0.0.6

* Add file `StoreResults` to upload cohort diagnostics zip to aws s3 bucket
* Update `KeyringSetup` to match `Ulysses`
* Update renv.lock to add `aws.s3` and `Ulysses` v0.0.2
* minor correction to study task files

# EHDEN HMB v0.0.5

* Add in renv
* minor correction to HMB cohort for cohort diagnostics

# EHDEN HMB v0.0.4

* Fix errors in KeyringSetup.R file
* Fix cohort diagnostics to use integer64 with id in cohortDefinitionSet

# EHDEN HMB v0.0.3

* Update How to run file with installation instructions for usethis and Ulysses
* Fix extras/KeyringSetup.R file to correctly set up credentials and check them
* Edit `startSnowflakeSession` function to handle string split of workDatabaseSchema
* Edit study tasks to order snowflake start correctly and close connection at end of file

# EHDEN HMB v0.0.2

* Update cohort definition for HMB to fix error
* Add cohort diagnostics script
* Add How to Run file and key ring file

# EHDEN HMB v0.0.1

* Add HMB cohort definition to repo
* Start preparing documentation about study
* Initialize OHDSI study
* Add `NEWS.md` to 
